alias idea="/home/nexus/Downloads/idea-IU-183.5912.21/bin/idea.sh"
alias clion="/home/nexus/Downloads/clion-2018.3.4/bin/clion.sh"
alias pycharm="/home/nexus/Downloads/pycharm-2018.3.5/bin/pycharm.sh"
alias webstorm="/home/nexus/Downloads/WebStorm-183.5912.23/bin/webstorm.sh"
alias harakiri="shutdown now"
alias tryagain="shutdown now -r"
alias aliasfish="vim ~/.config/fish/config.fish"
