#put me in ~/.config/fish/config.fish
alias idea="/home/nexus/Downloads/idea-IU-183.5912.21/bin/idea.sh"
alias clion="/home/nexus/Downloads/clion-2018.3.4/bin/clion.sh"
alias pycharm="/home/nexus/Downloads/pycharm-2019.1.1/bin/pycharm.sh"
alias webstorm="/home/nexus/Downloads/WebStorm-183.5912.23/bin/webstorm.sh"
alias harakiri="shutdown now"
alias tryagain="shutdown now -r"
alias aliasfish="vim ~/.config/fish/config.fish"
alias catz="/home/nexus/CLionProjects/Catz/cmake-build-debug/Catz"
alias termiteconf="vim /home/nexus/.config/termite/config"
alias i3config="vim ~/.i3/config"
alias diamond="/usr/local/diamond/3.10_x64/bin/lin64/diamond"
